version: '3.1'

services:
#database engine service
  redis:
#    container_name: redis
    image: redis:4.0-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    container_name: db
    image: mysql:8.4 # O cualquier otra imagen de DB compatible
    ports:
      - "3306:3306" # Mapear puerto para acceso externo si es necesario (opcional)
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Contraseña de root para MySQL
      MYSQL_DATABASE: test_db            # Base de datos que usará Codeception y PdoManager en tests
      MYSQL_USER: test_user              # Usuario para la base de datos de tests
      MYSQL_PASSWORD: test_password      # Contraseña para el usuario de tests
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./dbfiles:/docker-entrypoint-initdb.d
    healthcheck: # Comprobación de salud para asegurar que la DB está lista
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 10s
      retries: 5
  app:
    build:
      context: ./images/web
      dockerfile: Dockerfile
    container_name: app
    environment:
      COMPOSER_AUTH: '{"github-oauth": {"github.com": "${githubtoken}"}}'
      DB_HOST: db
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASS: test_password
      DB_CHARSET: utf8mb4
      REDIS_HOST: 'redis'
      JWT_URL: 'https://web.manresa.cat/api/usuaris/public_cert.php'
    expose:
      - "9000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./images/web/src/:/var/www/html/src
      - ./images/web/vendor:/var/www/html/vendor/
      - ./images/web/composer.json:/var/www/html/composer.json
  web:
    image: nginx:latest
    container_name: nginx-api
    ports:
      - "8080:80"
    volumes:
      - ./images/web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app